#!/usr/bin/env bash

_snapshot_make_completion() {
    local cur prev ids
    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="--bootable --integrity --sandbox"

    # First argument: subcommand
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
        return 0
    fi

    # Second argument: Name
    if [[ $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( "--name" )
        return 0
    fi

    return 0
}

# Bind completion to both valid command names
complete -F _snapshot_make_completion snapshot-make snapshot-make.sh
