#!/usr/bin/env bash

_preboot_completion() {
    local cur prev ids
    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="EnablePreboot DisablePreboot QueueUpdate DequeueUpdate EnableBgrt SetNextInstallmentScript"

    # First argument: subcommand
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
        return 0
    fi

    return 0
}

# Bind completion to both valid command names
complete -F _preboot_completion preboot preboot.sh
