#!/usr/bin/env bash

_snapshot_restore_completion() {
    local cur prev ids
    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="--system --home"

    # First argument: subcommand
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
        return 0
    fi


    # If -s is the previous argument, suggest snapshot IDs
    if [[ "${prev}${cur}" == "-s=" ]] || [[ ${#COMP_WORDS[@]} == 4 ]]; then
        ids="$("/opt/aqua/sys/sbin/snapshot-prober.sh" --list-simple 2>/dev/null)"
        COMPREPLY=( $(compgen -W "${ids}" -- "$cur") )
        return 0
    fi

    if [[ "${#COMP_WORDS[@]}" == 6 ]]; then
        COMPREPLY=( "<path>" )
        return 0
    fi

    # Dynamic <id> completion for commands requiring ID
    if [[ "${COMP_WORDS[2]}" != "-s" ]] && [[ ${#COMP_WORDS[@]} -ne 4 ]] ; then
        case "${COMP_WORDS[1]}" in
            --home)
                COMPREPLY=( "-s=" )
                return 0
                ;;
        esac
    fi

    return 0
}

# Bind completion to both valid command names
complete -F _snapshot_restore_completion snapshot-restore snapshot-restore.sh
