#!/usr/bin/env bash

_snapshot_prober_completion() {
    local cur prev ids
    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="--reconstruct-grub --list-simple"

    # First argument: subcommand
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
        return 0
    fi

    return 0
}

# Bind completion to both valid command names
complete -F _snapshot_prober_completion snapshot-prober snapshot-prober.sh
